### ISSUE TITLE
JOSM can't read GeoJSON saved from JOSM!

### ISSUE THREAD

**Issue by antifa-ev** [JOSM/geojson#14]
I use geojson 84 with JOSM 14026 (JRE 9) and can't open any GeoJSON again which I just saved from JOSM. Here is a basic non-working example:

```
{
    "type": "FeatureCollection",
    "generator": "JOSM",
    "features": [
        {
            "type": "Feature",
            "properties": null,
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        -116.09484157521,
                        30.70279722039
                    ],
                    [
                        -116.07013790490,
                        30.70333789611
                    ]
                ]
            }
        }
    ]
}
```

I assume that it's because the line
`"properties": null,`
in the json.

Anyone else with this problem?

**Comment by simonpoole** [comment]
See https://help.openstreetmap.org/questions/64197/geojson-not-working-in-josm-but-at-geojsonio

**Comment by csytsma** [comment]
The problem appears to be the file extension.  If you change it do just ".json", removing the 'geo' in front, then it will open.

**Comment by ovruni** [comment]
I had the same problem, remove '"properties": null,' allows me to open the file.

**Comment by don-vip** [comment]
@jreijn with latest changes the example described in this ticket results in following exception:

```
java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonObject
java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonObject
        at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonObject(JsonObjectBuilderImpl.java:242)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.getTags(GeoJsonReader.java:228)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.fillTagsFromFeature(GeoJsonReader.java:217)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.parseLineString(GeoJsonReader.java:145)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.parseGeometry(GeoJsonReader.java:107)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.parseFeature(GeoJsonReader.java:88)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.parseFeatureCollection(GeoJsonReader.java:81)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.parseRoot(GeoJsonReader.java:64)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.parse(GeoJsonReader.java:55)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonReader.doParseDataSet(GeoJsonReader.java:240)
        at org.openstreetmap.josm.plugins.geojson.GeoJsonFileImporter.importData(GeoJsonFileImporter.java:46)
        at org.openstreetmap.josm.gui.io.importexport.FileImporter.importDataHandleExceptions(FileImporter.java:95)
```
